language: minimal
services:
  - docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "u7nDVlgB1LKRy65coBJ87BwjUbSPlFRnoxXiUF+kaATF3hwati+023URfR65WpvGKSEc2yybRiytMIdFTRKu8ssNn21RkxoHU/jwiwfYxtlQZiFZULxb0mBLtLEn6BxrZxwNwYcR+DP8vlhPZ9RJ2ATpl53s2VTkErV/GZUTIG7IvpxRQR7GxzXwItCXkzIDyF7hzYskDEkBDWJRXUgCa8mg7YtiLrqxlJoDnQ3PDX47fI0Gzj1pDA3pHD+/NksryZo/X9GwMaBN5U/P+sDY/JMEQf1SCyPE+hkvrZdTizrUy/ydDmRP938R8TBBqouWzcTVOQ/yLw+GFVXyaIli7FeUTputsTIjTD9OE0jyxWmKG5aUusJE+KtBoOP+TP9pYwyit4o/Epr42b07GhuicHoC9/df3Z8ioz+5OSm8eL7zjUrHrOqgeVNv3dcML5wUfqzAObOPy1Ypk+WVFwoNCP3uA4UbivH+jdJbdcgVrgarxwnPh0xH4CwQvE4N3CYhk/3kbG278NaC9ztMsQnQuGoLsD0tNp/wRXL+hGhdcX0mzfoBtZegW5BRFQ6hGt7LBNQp4XvM4+p8OjQED+faSrs6e0vLaSK+pmifZ5dj6dixUNZZ/i0ZQweeXO/0Mh0LeG+XxqmTtndbWBh3/stBvh5Gash9ZqH6HBGsGkZ+3Dw="
    # AWS_SECRET_ACCESS_KEY
    - secure: "oWhLno3gnK1FtAx4QttZKXAyEhcfASFsxpaN9hXQrcx+4Ep33LRTMlSdxVcZjx7IULu4YjPPjdtEqhfjX1WSGJ8ZnVPArDqqOuPMCDDBKgveZ8g9yRytJ6nF9VV8tFxzjdzCDEAFFGA810qOu8qJ6EtbdGJ7Y4QRwL63x83DZcLZt7jefGLVydaTVq5IC8lwvKiNb3C+3MZLnUWZlJankDb3iMuPCmr8aaCnEH9OUvLedGpn0EiepYYyOADrzV7RIotYwZe18SDw1afdF1NvOu5zJ6gEdjlNKtSJ06m/Jh3ZFO+unIJvOaEn/9ST2ESuIYb/q590fjrUHhPhVLfLluCJuVEPuErMnS8SWRUhqNBVjqGpRbYye1T56BQQyQ/Ml4XQ4z//6k/yXDdL0rrUS47bxpVt/Zcm9Yd5W+Fh1yqpdtxmfGyKnwSCAxUbiMpu1H2xqmoH+6XGdHe9NH9maewpSAs0pSEa5KGjP6gTUQywAm9zKn8T+slgMdqVgQi6w6tFt03UtiYYVb+A7IIokfN0+VzlbDDdfyYhwazXr7blV63zR97jtD+T6eA2s6uavnNgcGFWS1AUPCC9p4GmadbQWZlgZ8fn4QLk1xM1V9XtKvn/d9nieCf+4xlNONNAppWhYJ9rvJ6gcFhCD10xeXu1SbsVowZ25HCDW+8c8s4="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh

script:
  - docker pull postgres:12
  - docker tag postgres:12 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:12

deploy:
  - provider: script
    script: docker push 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:12
    on:
      all_branches: true
