name: Kakuttaja

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 3'
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-and-deploy-container-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare container images
        shell: bash
        run: |

          docker build -t 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:11 --build-arg POSTGRES_VERSION=11 dockerfiles/postgres
          docker build -t 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:12 --build-arg POSTGRES_VERSION=12 dockerfiles/postgres
          docker pull redis:5.0
          docker tag redis:5.0 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/redis:5.0
          docker pull localstack/localstack:0.10.2
          docker tag localstack/localstack:0.10.2 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/localstack:0.10.2
          docker pull busybox:latest
          docker tag busybox:latest 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/busybox:latest
      - name: Deploy container images to ECR
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 190073735177.dkr.ecr.eu-west-1.amazonaws.com
          docker push 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:11
          docker push 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/postgres:12
          docker push 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/redis:5.0
          docker push 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/localstack:0.10.2
          docker push 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility/busybox:latest
